### ISSUE TITLE
Ability to attach files from editor

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-attachable#16]
Currently it's only possible to attach files from the browse, add the ability to do it from the editor.

**Comment by mariodavid** [comment]
Hi, 

It is already possible. See https://github.com/mariodavid/cuba-component-attachable/blob/master/modules/web/src/de/diedavids/cuba/attachable/web/annotationexecutor/WithAttachmentsEditorAnnotationExecutor.groovy

You have to extend AnnotatableAbstractEditor and define a buttonspanel where the button should be placed in.

Bye
Mario

**Comment by innovaringenieria** [comment]
but what is reported in the [forum](https://www.cuba-platform.com/discuss/t/dont-attach-file/5878) does not work
